### ISSUE TITLE
esp32cam injection

### ISSUE THREAD

**Issue by tair-rhyme** [rkinnett/ESP32-2-Way-Audio-Relay#2]
Hi.
Is it possible to implement video streaming with two way audio?
Thank you!

**Comment by rkinnett** [comment]
Depends on your hardware and coding skills.  I feel like the ESP32 is almost overloaded with this 2-way audio application as-is.  I wouldn't guess that you could stream video in parallel, but frankly I have no idea.

Closing as off-topic.  For general discussion you can reach me on discord:  http://discord.gg/C9EuvvfGZP
